### ISSUE TITLE
Cleanup Part 3 - Facebook

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#21]
in some files I have found remains of the facebook function. "Facebook like" is but no longer included in the theme.

**Comment by Frumph** [comment]
yeah the functions/facebook.php file has those ones that are no longer used can be removed/deleted from the file


From: Kniebremser 
Sent: Tuesday, January 06, 2015 8:57 AM
To: Frumph/comicpress 
Subject: [comicpress] Cleanup Part 3 - Facebook (#21)

in some files I have found remains of the facebook function. "Facebook like" is but no longer included in the theme.

**Comment by kniebremser** [comment]
facebook residues are removed
