### ISSUE TITLE
Claenup Part 4

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#22]
In the file facebook.php is still the function:

function opengraph_make_thumbnail_for_youtube()

 I do not know where else is needed?
Youtube works in WP complete with Embed.

Regards

**Comment by Frumph** [comment]
oembed with wordpress is not the same as facebook's opengraph ..

basically what *this* does is create an image for facebook to grab if you have a youtube video in your / as your comic ..

for example, with comic easel you can create a comic; that's a youtube video.  (*or have it in the post*) and when you link to the post from within facebook it will *not* recognize that there's a video there, so this code creates an image that you can use

**Comment by kniebremser** [comment]
Ok.

in avatar.php is the function: function easel_random_default_avatar
in comment-functions.php is: function easel_avatar()

Would it not be better, both functions in one file?

**Comment by Frumph** [comment]
some sites that were custom uses the random avatar outside of the comment-functions

**Comment by kniebremser** [comment]
O.K.
