### ISSUE TITLE
errors in js files according to jshint

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#26]
Aptana Studio shows me several warnings in the js files. There are said to be missing in several places semicolons.

in ddsmoothmenu.js at several points     see #27  update to new version
in instant.js line 44 and line 416              see #28  update to new version
in jquery.cycle.js line 1 several times

I have all *.js files in the folder "js" checked on http://jshint.com . There they are the syntax error has been confirmed. There are still to come further warnings.

Is done:
googletranslate.js                             delete "new" is fixed
menubar.js                                        nothing to do
scroll.js line 3 and line 27                 missing semikolons is fixed
cvi_text_lib.js                                    update to new version 1.03 -> jshint still shows after 4 warnings

**Comment by kniebremser** [comment]
I have the js files checked on http://jshint.com  . There they are the syntax error has been confirmed. There are still to come further warnings.

**Comment by Frumph** [comment]
Thank you for fixing!

**Comment by kniebremser** [comment]
Can you at times the jquery.cycle.js look. In line 1 should 6 semicolons are missing.
I have no idea at what points.
Or is there a new version of this file?

**Comment by kniebremser** [comment]
i marked this fixed. I create a new issue for the file jquery.cycle.js

**Comment by Frumph** [comment]
I have no idea where that jquery.cycle.js comes from, I don't remember if I even use that in the theme .. although it has 'slider' code in there, but that first line in the file is an 'eval' which shouldn't be there
