### ISSUE TITLE
update ddsmoothmenu.js from version 1.4 to version v2.2

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#27]
Can we this update?
See: http://www.dynamicdrive.com/dynamicindex1/ddsmoothmenu.htm
Version 1.4 has many faults, according jshint.com about 52 warnings
Version 2.2 has according jshint.com only 13 warnings.

**Comment by Frumph** [comment]
I'm not sure, i'll give it a try on the dev machine

**Comment by Frumph** [comment]
Unfortunately it didn't work with a straight transfer, I remember I did do a lot of modding to it

**Comment by kniebremser** [comment]
OK. I started in the old version to rectify the error. Many Works! On jshint.com online no errors are displayed.

**Comment by kniebremser** [comment]
done. the syntax errors according Jshint.com are eliminated.
