### ISSUE TITLE
missing value for a label in costumize.php

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#29]
in the file functions/costumize.php line 144 there is no "default" value for label.
Intent or failure?

**Comment by kniebremser** [comment]
This is meantime line 154: 
$css_array[] = array('slug' => 'comic_wrap_textcolor', 'description' => '#comic-wrap', 'section' => 'comicpress-text-colors', 'label' => '');
This is the only line with no 'default' at the end
'comicpress-text-colors', 'label' => '', 'default' => '');
That irritates me a little.
This affects only comiceasel costumize.

**Comment by Frumph** [comment]
You can fix any irritations you want to ;)

**Comment by kniebremser** [comment]
it's closed
