### ISSUE TITLE
Navkey.js not working , can't use arrow keys to navigate

### ISSUE THREAD

**Issue by LunaP** [Frumph/comicpress#30]
Using the latest Comicpress 4.2.2 and noticed that the arrow keys aren't allowing for navigation.
I've checked the settings under comic config, and comicpress config. Its active.

I tried calling the js manually but no go. Any ideas or suggestions on how I could troubleshoot this? Tried reinstalling a few times no dice.

**Comment by Frumph** [comment]
This is a Comic Easel issue and I have tested it on the current and it's working just fine, problem with unix-machine browsers though then it keeps working when tabbed to another window ;/

**Comment by LunaP** [comment]
Doesn't work in Chrome/Firefox/palemoon/IE/opera. I'm running windows, and haven't verified with anyone running linux. Any reason this was closed? Any troubleshooting tips you could suggest? Hoping it won't take another 2 months to respond.

**Comment by Frumph** [comment]
it was closed because comicpress does not have a navkey.js - refer to new ticket - while I understand that it's important to have the help for it - there are different people working on both projects and the issues need to be where they need to go properly
