### ISSUE TITLE
in widget multisite incomplete class name?

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#31]
In line 12 is:
class widget_multisite_sitelist extends WP_Widget {

would not mean, as in the other widgets:
class comicpress_multisite_sitelist _widget extends WP_Widget {

**Comment by Frumph** [comment]
changing the classname since the __CLASS__ uses the class name for the ID would make it so that people who already are using the widget lose their widget from the sidebar and have to replace it again [ happened to the navigation widget on it's rename =( ]  so i'm trying to avoid that (now) - although I have no idea if anyone is using that widget?

**Comment by kniebremser** [comment]
Hey Philip!
Sorry, I did not make myself clear only. There is no error.
I am porting the changes in the widgets for easel across it. In the other widgets, the class name has another structure. German correctness.

**Comment by Frumph** [comment]
I answered it as such, the error comes from changing the class name

**Comment by kniebremser** [comment]
So let's leave it as it is.
What about? #29 missing value for a label in costumize.php
In the line 146 is no label stated. Is this intentional? 
This is the only $ css_array [] without label

**Comment by kniebremser** [comment]
see screenshot:
![ice_screenshot_20150818-225541](https://cloud.githubusercontent.com/assets/4800726/9342528/85d14a62-45fc-11e5-9c08-1db807de2ead.png)

**Comment by Frumph** [comment]
just means I didn't know what text to put there ;/

**Comment by kniebremser** [comment]
instead of:
'comicpress-text-colors', 'label' => '');
'comicpress-text-colors', 'label' => '', 'default' => '');
That irritates me a little. It's the only line where "default" is not specified.

**Comment by Frumph** [comment]
^ name for class name for multisite fixed
