### ISSUE TITLE
bad language identifier somewhere showing up in the report as 'comicpress,comicpress' 

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#32]
I can't find where it's at, could you look around for it?
 
'comicpress,comicpress' is a _( identifier someplace

**Comment by kniebremser** [comment]
OK. I look tomorrow if I can find something to.

**Comment by kniebremser** [comment]
I have the whole directory scanned with different search parameters.
Nothing found.
Which app has reported the error?

**Comment by Frumph** [comment]
Plugin:  Theme Check

INFO: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are comicpress,comicpress

**Comment by Frumph** [comment]
https://github.com/Otto42/theme-check/issues/83

**Comment by Otto42** [comment]
This is the line with the issue:

https://github.com/Frumph/comicpress/blob/master/comments.php#L67

**Comment by kniebremser** [comment]
The line is fixed.
