### ISSUE TITLE
cleanup for style.css

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#34]
I have looked at times the style.css accurate.
In several places I have not mentioned css-settings found.
Since prolonged use Firefox and Chrome CSS3 values.
-moz-border-radius and -webkit-border-radius are not needed.
Both browsers use -border-radius.
For -webkit-linear-gradient (linear, left top, left bottom, from (#aaa) to (#EEE)) gives a warning: Invalid Property Value.

Thus, the style.css could be slightly slimmer.

**Comment by Frumph** [comment]
-webkit is still used in older android pre<ver. 2.3 just read up on it.. but, not like I care right?  they can update chrome and it will work fine on those androids

So, removing values per your advice, going to get rid of all three, -moz -khtml and -webkit for border-radius for the first phase, then i'm going to read up on box-shadow

**Comment by Frumph** [comment]
text-shadow opacity box-shadow AND border-radius are all cleaned up and the -moz -khtml and -webkit's removed

per this website:  http://caniuse.com/#
