### ISSUE TITLE
reminder to knie and kristi

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#35]
Please edit the style.css to add your wordpress.org username (capital first letter) under Contributors: section comma separated..

And additionally editing the readme.txt with info about yourself, links, email etc.  (i'll do mine as well)

-- and knie if you can find time to update the changelog from last release to this future one - if not I can do it, basically looking at all of the submits and tagging each and everyone one *

**Comment by kniebremser** [comment]
is done.

**Comment by Frumph** [comment]
reopening for kristi ;/ (new person on team)
