### ISSUE TITLE
error in function mood_admin_function

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#36]
I have a error warning in wp-admin with ComicPress and WordPress 4.4 trunk.

warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'mood_admin_function' not found or invalid function name in E:\htdocs\WordPress\wp-includes\plugin.php on line 503

**Comment by Frumph** [comment]
.. weird, i thought I pushed that fix one sec

**Comment by Frumph** [comment]
Fixed https://github.com/Frumph/comicpress/commit/4cd2f84d82e4ea42063aa63c22e3eaeccdab2b24
