### ISSUE TITLE
errror in author.php or in wordpress?

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#38]
Hi Phil!
I again.
When I call the author's page at localhost dev install, I am redirected to my website in the net. Is this a bug in the theme or wordpress? Could not find anything. Wanted to look after easel # 24 (better layout for contact-infos in author.php) and then annoys the redirect.

**Comment by Frumph** [comment]
most likely a bug with your localhost install,   mouseover the link on your localhost install and see where it's going first

**Comment by kniebremser** [comment]
Sorry. Found error. Amounted on my install.
