### ISSUE TITLE
6 warnings for jquery.cycle.js according to Aptana Studio and jshint.com 

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#39]
Aptana Studio and jshint.com warning: 6 missing semicolons in line 1.
Because no file header is present. it's hard to find a further development.
But I have this found: jQuery Cycle Plugin. 
It would have significantly more potential effects. Perhaps it would also be available for comiceasel?
http://malsup.com/jquery/cycle/

**Comment by Frumph** [comment]
that jquery.cycle.js shouldn't (as far as I know) have been inside the theme at all,  I don't use it - if I do I have no idea where I even load it from ..

removed from the theme
