### ISSUE TITLE
better layout and more infos for contact-infos in author page

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#40]
The author page looks to me neglected.
I have a few ideas occurred.
Show ONLY for admin add:
- User role
- count of posts
- count of comments

The contact info to get the style of a business card with:
- Email (SHOW ONLY admin)
- Facebook
- Twitter
- Google+

The style is made on css. So it simple costumize the whole.

**Comment by kniebremser** [comment]
Hi Phil!

What do you think of the changes?

**Comment by Frumph** [comment]
Let's remove the dotted line around the biography information - otherwise looks good

**Comment by kniebremser** [comment]
is fixed
