### ISSUE TITLE
error in firefox with new style settings for content

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#42]
The changes breaks the content in posts and images.
I used the plugin nextgen gallery.
In pages and posts embedded a picture with fullsize. This breaks the content.

Before the changes, this has the content is not broken.
The picture was within the content.
Now the picture is much larger and also outside of content.
If a substantial css value deleted.

**Comment by Frumph** [comment]
Do you have a link so I can see it happening?

It's probably missing the max-width: 100%; on the image for nextgen, easy fix

**Comment by kniebremser** [comment]
css changes do not help. I must all the pictures in posts and pictures dimensioned.

**Comment by Frumph** [comment]
closed?

**Comment by kniebremser** [comment]
I am searching tonight after the deleted CSS value, which is responsible for it.

**Comment by kniebremser** [comment]
I have found the guilty items in the style.css.
Line 408 - Line 428
# content-column is reworked
# content is new

I have this in the style.css marked with the old settings ( uncommented) for # content-columns

**Comment by kniebremser** [comment]
It is a firefox error in Version 42 Beta1.
In Chrome and Edge no errors.
Hopefully the problem will be eliminated.

**Comment by kniebremser** [comment]
or missing the firefox somewhere a shit </div>

**Comment by Frumph** [comment]
Related:
https://bugzilla.mozilla.org/show_bug.cgi?id=975632

**Comment by Frumph** [comment]
Fixed, reverted to using fixed-widths on elements
