### ISSUE TITLE
spacer.png not displayed

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#43]
on localhost error: specified URL can not be loaded

**Comment by Frumph** [comment]
right click in browser, -> view source .. find spacer.png give me link it is trying to display and errors out from

**Comment by kniebremser** [comment]
the link is:
http://localhost/WordPress/%3C?%20echo%20get_template_directory_uri();%20?%3E/images/spacer.png

error in firefox 42 beta 1
firebug say: specified URL can not be loaded

**Comment by kniebremser** [comment]
I have a possible solution found. i hope this is right. My last commit.

**Comment by Frumph** [comment]
My mouse does the same thing.
