### ISSUE TITLE
removed outdated widget google translate in the next release

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#47]
The widget google translator is not more up-to-date.

The whole thing is doubledgemoppelt. In the browser, this function is integrated or retrofitted. And when a user needs this function, he enabled them to the service of their choice.
Since we do not need the Google Translator presetting him.

Google Chrome is the translations function integretad. (default Google, other possible)
Microsoft Edge is the translations function integretad. (with Bing, other possible)
Microsoft Explorer is the translations function integretad. (with Bing, other possible)
Firefox retrofittable via Add-On (various translation programs possible)
Apple Safari and Opera used Chromium via Add-On (various translation programs possible).

That's why this widget need no longer be present in the default theme.

If an admin who needed there for plugins that are more adaptable.

**Comment by Frumph** [comment]
Ok, i'm okay with it leaving,  can't just remove the widget though; have to edit functions.php as well
