### ISSUE TITLE
reworked widget classic bookmark in the next release

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#48]
The widget classic bookmark is outdated.
It is not easy customizable and acts as a relic of ancient times.
For admins who want to use this function, there is the plugin:
https://wordpress.org/plugins/favorites/

Pro arguments:
- is actively developed
- many settings
- output css is customizable
- Design is contemporary

**Comment by Frumph** [comment]
Con:
Actively used on 1000's of webcomic sites
Directly goes to the location you marked
Can be ignored and the plugin you mentioned above used instead without conflict

**Comment by kniebremser** [comment]
That's true also. OK. then eventually the whole spice. Have the renamed accordingly the issue.

**Comment by Frumph** [comment]
Note: we're still on 4.3 release, so any changes you make right now will affect 4.3 ...

**Comment by kniebremser** [comment]
Sorry. Since I was probably too fast. Become now my feet keep quiet.
The gifs have old name and are now the old location.
The other changes are bug fixes:
- removed unneeded translations function
- added needed translations function
- added alt tag for info.gif
- moved css style for help text info.gif to style.css

Have all tested. Works fine. Also likely to break anything.
The template .po file would again be updated.

**Comment by Frumph** [comment]
All good to close ticket?

**Comment by kniebremser** [comment]
For now closed
