### ISSUE TITLE
Trouble with blog and comic pages

### ISSUE THREAD

**Issue by Maegin2015** [Frumph/comicpress#49]
I recently installed the comicpress theme and comic easel plugin and uploadet some comics. I haven't downloadet wordpress - but used a 1-click install with my host. So I have no experience with uploading the files myself etc. - and no experience in coding.

I use the Comicpress theme and the Comic Easel plugin I think. I also have jetpack installed and wp super cache. At some point I also installed some plugin that had to do with migrating from Comic Press to Comic Easel or something like that. But I didn't know what it did, and I think I uninstalled it again. - So that should give you a good idea of my level of experience with wordpress ;)

 There is just something I can't get my head around: I want a page with my comic - and I want a page with a blog. I don't want the comic to be shown on the page for my blog posts. I just can't get this to work. Either the comic it shown on the blog page or is not shown at all. I would prefer it if I could get comic to appear on the homepage of course.

I've tried all kinds of combinations of "Disable Comic on the Home Page?", "Disable the Comic Post on the Home Page?", "Disable Blog Loop?" and the "static home page" (the latter under 'reading').

My page: http://webofwisdom.dk

 Can you help me?

 Best regards and thanks

 Jan

**Comment by Frumph** [comment]
can you go to settings -> permalinks and choose a permalink method and click save/update  so I can see what pages you setup in the menubar ?

**Comment by Maegin2015** [comment]
It is set to default: http://webofwisdom.dk/?p=123

**Comment by Frumph** [comment]
Yes, please set it to something other then default.

**Comment by Maegin2015** [comment]
Ok. Now it is set to sample post: http://webofwisdom.dk/sample-post/

**Comment by Maegin2015** [comment]
i.e. Post name :)

**Comment by Frumph** [comment]
The comic displaying on the 'blog' page might be a bug with Comic Easel, it shouldn't be displaying on that page.

**Comment by Frumph** [comment]
how did you setup the blog page, did you do it from settings -> reading ?

**Comment by Maegin2015** [comment]
Yep. It is set to a static page. The front page is 'comic' and the posts
page is 'blog'

Under the Comic Easel config I've set added the "Disable the Comic Post on
the Home Page"


I have not enabled "Disable Blog Loop". It reads "Enabling this option,
will DISABLE the blog from appearing on the home page AND any pages set as
the blog posts page in the settings ➔ reading."



Question:

The option "Disable Comic on the Home Page" reads "Checking this will stop
the display of the comic and comic area on the home page" - what is the
difference between the 'comic' and the 'comic area'?

I have not enabled this.

Also - is there a difference between 'comic', 'comic post' and 'comic area'?


Best regards,

Jan


On 1 October 2015 at 00:58, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> how did you setup the blog page, did you do it from settings -> reading ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144569217>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com

**Comment by Frumph** [comment]
.. disable what you did in settings -> reading, put it back to default nothing

create a page, page -> add new,  call it "Blog"  in the right column there's a dropdown box, look for a template called "blog"  tell me if you have it or not, if you do not, it's easy to create

- Phil

**Comment by Maegin2015** [comment]
Done... so far so good

Now there is no comic on the 'blog' page. But also no comic, when I press
the 'Comic' page to go back from the blog to the comic again.

Cheers, Jan :)

On 1 October 2015 at 10:54, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> .. disable what you did in settings -> reading, put it back to default
> nothing
>
> create a page, page -> add new, call it "Blog" in the right column there's
> a dropdown box, look for a template called "blog" tell me if you have it or
> not, if you do not, it's easy to create
>
>    - Phil
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144660015>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com

**Comment by Frumph** [comment]
When you click comic in the menubar it goes to this url:

http://webofwisdom.dk/web-of-wisdom-3/

it should go to:  http://webofwisdom.dk/

So, please fix your menubar

**Comment by Frumph** [comment]
YOu also disabled page titles in appearance -> comicpress options, as well as 'other' stuff that I need to see what's going on by being displayed

**Comment by Maegin2015** [comment]
Now page titles are back on.

I haven't touched the menubar (I'm not sure what it is). Where can I change
it to the right url?



On 1 October 2015 at 14:09, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> YOu also disabled page titles in appearance -> comicpress options, as well
> as 'other' stuff that I need to see what's going on by being displayed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144708764>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com

**Comment by Frumph** [comment]
Appearance -> menus

when you create a menu, you can choose what 'objects' go into the menu and then you select its [x] primary location.   the "view all" tab, there's a home option there, use that one, checkmark them and add them to menu

**Comment by Maegin2015** [comment]
Ok. Now I've added Home. It says custom link which is webofwisdom.dk

I've also added the pages to the menu... and saved it.

On 1 October 2015 at 14:26, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> Appearance -> menus
>
> when you create a menu, you can choose what 'objects' go into the menu and
> then you select its [x] primary location. the "view all" tab, there's a
> home option there, use that one, checkmark them and add them to menu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144711559>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com

**Comment by Frumph** [comment]
..didja assign it to the 'primary' menubar location?

**Comment by Maegin2015** [comment]
It is done... Now a 'home' page appeared

On 1 October 2015 at 15:52, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> ..didja assign it to the 'primary' menubar location?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144731991>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com

**Comment by Maegin2015** [comment]
Hi Philip.

NOW I got it to work - by trashing the 'comic' page and disabling blog
roll. So now the 'comic' page is replaced by the 'home' page.

Thank you SO much for your time and all your help!!

Best Regards,

Jan

On 1 October 2015 at 15:52, Philip M. Hofer (Frumph) <
notifications@github.com> wrote:

> ..didja assign it to the 'primary' menubar location?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Frumph/comicpress/issues/49#issuecomment-144731991>.
>



-- 
Jan Sørensen, Lecturer, Cand. Mag.
Garnisonsvej 8, 2. th.
3520 Farum
Mobil: +45 60 61 88 10
email: docstoj@gmail.com
