### ISSUE TITLE
TODO (pre 4.3 release)

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#50]
Customizer - take values of layout from old options and make them defaults in the customizer so when people update their sites don't look like crap

> done

Options (custom header size) - take values from customizer to set default width for headers

> done

CSS - figure out responsive problem with sandy and high schemes

**Comment by kniebremser** [comment]
For the costumizer issue have you a idea?

**Comment by Frumph** [comment]
Will hold off on CSS fix for sandy and high schemes for 4.4
