### ISSUE TITLE
Should we separate the 'general' tab into individual pages?

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#52]
e.g  post tab pages tab comments tab ?

**Comment by Frumph** [comment]
yeah making new tabs for each section right now

**Comment by Frumph** [comment]
options section now has more tabs, files are all yours to work in now if you wanted to do anything with them

**Comment by kniebremser** [comment]
I still have the menubar options reworked. The new options I look at the same.

**Comment by kniebremser** [comment]
The amendments are top. Is everything clear. Thumbs up. Nothing to complain about.

**Comment by kniebremser** [comment]
I have added to splash "First Steps". Can you even look at it, because text changes

**Comment by Frumph** [comment]
edited 

Should we add 'important things to know on upgrade' ?

**Comment by kniebremser** [comment]
yes. 
- Notice: your changes in the theme files are loosed. Please, used for changes a child theme.
- possibly pre-announcements for the next release e.g. moved the images of widget classic bookmark in a seperate directory

**Comment by Frumph** [comment]
.. shouldn't move the images of the classic bookmark widget, they're fine where they are in images/  don't need to subfolder everything ;/

**Comment by kniebremser** [comment]
that was just one example of content for 'important things to know on upgrade'.

when Big changes are planned in the next release (eg moved or deleted). So that can make the user changes the outset in his Childtheme.

**Comment by kniebremser** [comment]
or you want to embed the changelog?

**Comment by Frumph** [comment]
neg, TODO 4.4, move everything to customizer

will do blog posts for changes for now, next release use the notices for changelog, maybe read in the readme.txt
