### ISSUE TITLE
removed unused widgets

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#54]
in the folder are 2 dead widgets:
+ calender - this is integrated in comiceasel
+ dogecoins

can this removed?

**Comment by Frumph** [comment]
comicpress calender is for blog posts, not the same as the one in comic easel

dogecoins ... i remember some people using it, that's why I had it in there ;/

**Comment by kniebremser** [comment]
I just wonder, the Calender you have time off in Easel and since then he's just as .txt file in the directory.

**Comment by Frumph** [comment]
not everyone uses comic easel, with comicpress so the calendar is there - it's a good calendar

**Comment by kniebremser** [comment]
Then he can also be reactivated.

**Comment by kniebremser** [comment]
Make possible with a function that is only one Calender active.
comicpress -> comicpress calender
comicpress & comiceasel -> comicpress calender default disabled and comiceasel calender default enabled

**Comment by Frumph** [comment]
but they're both different, one is for comics (comic-easel), the other is for posts (comicpress)

**Comment by kniebremser** [comment]
then just reactivate

**Comment by kniebremser** [comment]
fixed

**Comment by Frumph** [comment]
awesome
