### ISSUE TITLE
change the logic in the costumizer

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#59]
Can we change the logic in the customizer. Not after textcolors, link colors, header image.
For newcomers, it is not easy, which is exactly meant by # setting if you do not know the code.

But according to areas:
1. header with header image and all colors
2. sidebars with possible widget costumize, When widget activated and all colors
4. content
5. Footer
6. Braedcumbs

For newcomers, it's easier. It has an area he wants to edit with any adjustment.

and simultaneously rearrange the entries aka the order the costumizer.
In the style.css add Hirachie (Table of Contents). so we get a few more bodies to the style track.

**Comment by Frumph** [comment]
header is controlled by wordpress

but yeah, there needs to be better 'word usage' on those .. notice I don't use label and description properly.. those need to be re-made to be better read

**Comment by kniebremser** [comment]
I have taken a few thoughts on how it may look reasonable.
Make for each area a own issue.
