### ISSUE TITLE
possible problems with the new costumizer?

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#66]
I have changed my dev-tool to eclipse mars. 
The App issues the following warnings:

Attribute name (min) must be followed by the '=' character.	customize.php	line 63	HTML Problem
Attribute value (var min='<?php echo $min; ?>';var max='<?php echo $max; ?>';
				if(this.focus){
					if(min!=''&&this.value<parseInt() not closed.	
								customize.php	line 61	HTML Problem
Invalid location of text (!) in tag (<input>).			customize.php	line 65	HTML Problem
Invalid location of text (() in tag (<input>).			customize.php	line 65	HTML Problem
Invalid location of text ()){) in tag (<input>).		customize.php	line 63	HTML Problem
Invalid location of text (}) in tag (<input>).			customize.php	line 65	HTML Problem
Invalid location of text (&&) in tag (<input>).			customize.php	line 65	HTML Problem
Undefined attribute name (else).				customize.php	line 65	HTML Problem
Undefined attribute name (if).					customize.php	line 65	HTML Problem
Undefined attribute name (ontouchmove).				customize.php	line 40	HTML Problem
Undefined attribute name (ontouchmove).				customize.php	line 59	HTML Problem
Undefined attribute name (this.value).				customize.php	line 64	HTML Problem
Undefined attribute name (this.value).				customize.php	line 65	HTML Problem

can be ignored?

**Comment by kmhcreative** [comment]
I'd say it can be ignored.  It looks to me like the dev tool parser is interpreting the inline javascript as HTML.  For example, that line 63 warning that looks like it's seeing javascript variable "min" as input tag attribute "min"

**Comment by Frumph** [comment]
Most dev tools do that, they have a difficult time separating the parsing of the two languages

**Comment by kniebremser** [comment]
OK. I think I understand. That dev tool outputs the warnings because inline JavaScript is not declared as such. The dev-tool missing open and closed script tags. That's why he thinks it's html. Can browsers misinterpret this also?

**Comment by kmhcreative** [comment]
I'm unaware of any browser that would parse the javascript code from the html incorrectly.  The onclick, onchange, ontouchstart, etc., tell it to expect javascript in the quotes after the "=" sign.  I believe the only place you'd ever declare the language inline would be "javascript:" inside the quotes of an anchor tag href so it knows not to interpret it as a URL.  HTML5 assumes all scripting of undeclared type is javascript - it doesn't even require the type="text/javascript" declarations in script tag blocks anymore.

The parser may also be getting confused by the fact there is are newlines inside the quotes for the onchange (for human readability of the code).  If the newlines were removed so the code block was literally all on one long line, it might parse it correctly.

**Comment by kniebremser** [comment]
OK. So closed.
