### ISSUE TITLE
copywrite.php file error:  go to top

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#67]
For some reason somewhere along the line it got changed to #outside  ;/ so noones 'go to top' is working anymore.

Need to find an older copy of comicpress and see how i'm doing that to refresh my memory.

**Comment by Frumph** [comment]
erm copyright.php

**Comment by kniebremser** [comment]
change from:
$output .= "<a href=\"#outside\" onclick=\"scrollup(); return false;\">"
to: 
$output .= "<a href=\"\" onclick=\"scrollup(); return false;\">"
fixed the issue. tested with Firefox, Chrome and Edge

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://hilowdeals.com/estate.php?b3>

 

hello@mookiecreative.com

**Comment by m00k1e** [comment]
Hello!

 

New message, please read <http://kamensky.eu/fragile.php?ii>

 

hello@mookiecreative.com
