### ISSUE TITLE
note to fix translation string:

### ISSUE THREAD

**Issue by Frumph** [Frumph/comicpress#76]
https://github.com/Frumph/comicpress/blob/master/functions/copyright.php#L12

needs to be set in translationable string

**Comment by Frumph** [comment]
Question, does RSS need to be a translation string?  is that the same in all languages?

**Comment by Frumph** [comment]
I am referring to the one in the translation string

**Comment by kniebremser** [comment]
I've tried to get it, but I always make a php mistake. My idea of ​​php is also limited.

**Comment by Frumph** [comment]
don't mind that, the question though is RSS really needed to be translatable?

**Comment by kniebremser** [comment]
I've translated "RSS" into various languages ​​(Japanese, Chinese, Afrikaans) with google translate. I was always shown "RSS". "RSS" is also an international standard.
For us, we can leave it that way for now.
We can keep that in mind.

**Comment by Frumph** [comment]
sounds great, glad for the confirmation thank you, closing this

**Comment by kniebremser** [comment]
Have found the solution
