### ISSUE TITLE
Activation as editor for translations at wordpress

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#78]
Can you activate me as an editor for German translations (default and formal) on WordPress? 

https://translate.wordpress.org/locale/de/default/wp-themes/comicpress/

Then we could also remove the translation files from the plugin. Once 95% of a language is translated, WordPress will update the translation file alone. This is also stored outside of the theme.
That would be less work.

**Comment by Frumph** [comment]
yes I would def. if I had that ability, .... but I just searched everywhere and couldn't figure out where to add someone

**Comment by kniebremser** [comment]
https://translate.wordpress.org/projects/wp-themes/comicpress/contributors/

maybe on this page

**Comment by Frumph** [comment]
it shows you are a contributor on that page, and the 'make' is just a blog pretty much

**Comment by kniebremser** [comment]
I've filed a change there waiting for an editor to unlock it. And I need those rights. With the PTE (Project Translation Editor) rights, any change will be applied immediately.

https://make.wordpress.org/polyglots/handbook/rosetta/roles-and-capabilities/pte-request/#pte-request-by-a-plugintheme-author

I would need the activation for de.de (default) and de.de (formal)

**Comment by kniebremser** [comment]
I asked, did not get an answer, but an editor made changes in the translations or deleted them.
I think so I wanted to tell me that I get no PTE rights.
For this kind of treatment, I gave my PTE rights to the wp-optimize plugin.
We can consider that done.

**Comment by kniebremser** [comment]
So on Monday I was unlocked as an editor.

**Comment by Frumph** [comment]
nice!
