### ISSUE TITLE
blank space for text "moods are available"

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#79]
https://github.com/Frumph/comicpress/blob/b2bb957e7c887a1978350d82e265445e67b54837/functions/moods.php#L72

The blank space at the beginning of the text should be commented out by the text.
In translation, the space could be forgotten.
then it might look like this: 5moods are available.
correct would be: 5 moods are available.

Unfortunately I can not test it because I do not use moods

**Comment by Frumph** [comment]
`
echo $count .'&nbsp;'.__( 'moods are available.', 'comicpress' ).'<br />
`

the . means to 'add this to the current statement' sort of attitude  the nbsp; is the ascii character for space so that should work yah?

**Comment by kniebremser** [comment]
`echo $count . ' '. __( 'moods are available.', 'comicpress' ).'<br />`

I would favor this solution.
