### ISSUE TITLE
delete translation string for theme discription

### ISSUE THREAD

**Issue by kniebremser** [Frumph/comicpress#84]
The function for the Theme Discription in functions.php line 422 can be removed because it is now superfluous. Wordpress gets the string to translate from style.css.

Could you please do that before I do damage again?

**Comment by Frumph** [comment]
..wordpress always got that string from style.css though.. no idea where that even came from ;/

**Comment by kniebremser** [comment]
We inserted that before the WordPress Translate website was available.
Now the whole thing is superfluous.
